const CAPABILITIES = Object.freeze({
  DASHBOARD_VIEW: 'dashboard.view',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_ADJUST: 'inventory.adjust',
  RECEPTION_READ: 'reception.read',
  RECEPTION_CREATE: 'reception.create',
  RECEPTION_CONFIRM: 'reception.confirm',
  PURCHASE_ORDER_CANCEL: 'purchase_order.cancel',
  PRODUCTION_READ: 'production.read',
  PRODUCTION_RELEASE: 'production.release',
  PRODUCTION_PICK: 'production.pick',
  PRODUCTION_ADVANCE: 'production.advance',
  PRODUCTION_CLOSE: 'production.close',
  OUTSOURCING_READ: 'outsourcing.read',
  OUTSOURCING_MANAGE: 'outsourcing.manage',
  OUTSOURCING_RECEIVE: 'outsourcing.receive',
  DISPATCH_READ: 'dispatch.read',
  DISPATCH_REQUEST: 'dispatch.request',
  DISPATCH_CONFIRM: 'dispatch.confirm',
  RETURNS_READ: 'returns.read',
  RETURNS_MANAGE: 'returns.manage',
  WASTE_READ: 'waste.read',
  WASTE_REPORT: 'waste.report',
  APPROVALS_READ: 'approvals.read',
  APPROVALS_DECIDE: 'approvals.decide',
  CATALOG_READ: 'catalog.read',
  CATALOG_MANAGE: 'catalog.manage',
  SIIGO_READ: 'siigo.read',
  SIIGO_POLL: 'siigo.poll',
  SIIGO_SYNC: 'siigo.sync',
  WEBHOOK_LOGS_READ: 'webhook.logs.read',
  USERS_MANAGE: 'users.manage',
});

const READ_ONLY = [
  CAPABILITIES.DASHBOARD_VIEW,
  CAPABILITIES.INVENTORY_READ,
  CAPABILITIES.RECEPTION_READ,
  CAPABILITIES.PRODUCTION_READ,
  CAPABILITIES.OUTSOURCING_READ,
  CAPABILITIES.DISPATCH_READ,
  CAPABILITIES.RETURNS_READ,
  CAPABILITIES.WASTE_READ,
  CAPABILITIES.CATALOG_READ,
  CAPABILITIES.SIIGO_READ,
];

// Legacy roles retain their current access while users are migrated to the
// workflow-specific roles. New roles are intentionally least-privileged.
const ROLE_CAPABILITIES = Object.freeze({
  admin: ['*'],
  administrador: ['*'],
  supervisor: ['*'],
  validador: [
    ...READ_ONLY,
    CAPABILITIES.APPROVALS_READ,
    CAPABILITIES.APPROVALS_DECIDE,
  ],
  operario: [
    ...READ_ONLY,
    CAPABILITIES.RECEPTION_CREATE,
    CAPABILITIES.RECEPTION_CONFIRM,
    CAPABILITIES.PRODUCTION_RELEASE,
    CAPABILITIES.PRODUCTION_PICK,
    CAPABILITIES.PRODUCTION_ADVANCE,
    CAPABILITIES.PRODUCTION_CLOSE,
    CAPABILITIES.DISPATCH_REQUEST,
    CAPABILITIES.DISPATCH_CONFIRM,
    CAPABILITIES.RETURNS_MANAGE,
    CAPABILITIES.WASTE_REPORT,
    CAPABILITIES.SIIGO_POLL,
  ],
  consulta: READ_ONLY,
  recepcion_cierre: [
    ...READ_ONLY,
    CAPABILITIES.RECEPTION_CREATE,
    CAPABILITIES.RECEPTION_CONFIRM,
    CAPABILITIES.PRODUCTION_CLOSE,
    CAPABILITIES.OUTSOURCING_RECEIVE,
    CAPABILITIES.WASTE_REPORT,
  ],
  alistador: [
    ...READ_ONLY,
    CAPABILITIES.PRODUCTION_PICK,
    CAPABILITIES.PRODUCTION_ADVANCE,
    CAPABILITIES.WASTE_REPORT,
  ],
  despacho: [
    ...READ_ONLY,
    CAPABILITIES.DISPATCH_CONFIRM,
    CAPABILITIES.RETURNS_MANAGE,
    CAPABILITIES.SIIGO_POLL,
  ],
});

const ACTION_CAPABILITIES = Object.freeze({
  INGRESO_RECEPCION: CAPABILITIES.RECEPTION_CONFIRM,
  SOLICITAR_INICIO_PRODUCCION: CAPABILITIES.PRODUCTION_RELEASE,
  LIBERAR_ORDEN_PRODUCCION: CAPABILITIES.PRODUCTION_RELEASE,
  AVANCE_FASES: CAPABILITIES.PRODUCTION_ADVANCE,
  REPORTE_MERMA: CAPABILITIES.WASTE_REPORT,
  SOLICITAR_CIERRE_PRODUCCION: CAPABILITIES.PRODUCTION_CLOSE,
  CERRAR_ORDEN_PRODUCCION: CAPABILITIES.PRODUCTION_CLOSE,
  SOLICITAR_DESPACHO: CAPABILITIES.DISPATCH_REQUEST,
  CONFIRMAR_MATERIALES_PRODUCCION: CAPABILITIES.PRODUCTION_PICK,
  EXCEPCION_PICKING: CAPABILITIES.PRODUCTION_PICK,
  AJUSTAR_MATERIALES_PRODUCCION: CAPABILITIES.PRODUCTION_PICK,
  GESTION_DEVOLUCION: CAPABILITIES.RETURNS_MANAGE,
  CONSULTAR_STOCK_MATERIA_PRIMA: CAPABILITIES.INVENTORY_READ,
  CONSULTAR_STOCK_PRODUCTO_TERMINADO: CAPABILITIES.INVENTORY_READ,
  CONSULTAR_ESTADO_PRODUCCION: CAPABILITIES.PRODUCTION_READ,
  CONSULTAR_TRAZABILIDAD_LOTE: CAPABILITIES.INVENTORY_READ,
  CONSULTAR_CAPACIDAD_FABRICACION: CAPABILITIES.PRODUCTION_READ,
  MODO_CHARLA: CAPABILITIES.DASHBOARD_VIEW,
  APROBAR_SOLICITUD: CAPABILITIES.APPROVALS_DECIDE,
  RECHAZAR_SOLICITUD: CAPABILITIES.APPROVALS_DECIDE,
  AJUSTE_INVENTARIO: CAPABILITIES.INVENTORY_ADJUST,
  CONSULTAR_SOLICITUDES_PENDIENTES: CAPABILITIES.APPROVALS_READ,
  SINCRONIZAR_FACTURAS_SIIGO: CAPABILITIES.SIIGO_POLL,
  CONFIRMAR_DESPACHO_SIIGO: CAPABILITIES.DISPATCH_CONFIRM,
  REGISTRAR_BORRADOR_SALIDA_3Q_DOCUMENTO: CAPABILITIES.OUTSOURCING_MANAGE,
});

function normalizeRole(role) {
  return String(role || '').trim().toLowerCase();
}

function capabilitiesForRole(role) {
  return ROLE_CAPABILITIES[normalizeRole(role)] || [];
}

function hasCapability(role, capability) {
  const capabilities = capabilitiesForRole(role);
  return capabilities.includes('*') || capabilities.includes(capability);
}

function capabilityForAction(action) {
  return ACTION_CAPABILITIES[String(action || '').trim().toUpperCase()] || null;
}

module.exports = {
  CAPABILITIES,
  ROLE_CAPABILITIES,
  ACTION_CAPABILITIES,
  normalizeRole,
  capabilitiesForRole,
  hasCapability,
  capabilityForAction,
};
